INSERT INTO USUARIO VALUES(NULL,'ANDRADE','ANDRADE2009','HEXACAMPEAO');
INSERT INTO USUARIO VALUES(NULL,'MARCOS','MARCOS.2020','12458547aS@');
INSERT INTO USUARIO VALUES(NULL,'ADRIANO','ADRIRADIOLOGISTA','ATOMY2021');
INSERT INTO USUARIO VALUES(NULL,'NEIDEFFERREIRA','ANDRADE2009','HEXACAMPEAO');
INSERT INTO USUARIO VALUES(NULL,'LAURA_BEE','LAURA_BEE','4975DFHJID');
INSERT INTO USUARIO VALUES(NULL,'SANDRO','SANDRO2009','HEXACAMPEAO');
INSERT INTO USUARIO VALUES(NULL,'ROBERVAL','ROBERVAL2009','HEXACAMPEAO');
INSERT INTO USUARIO VALUES(NULL,'ADRENALINA','ADRENALINA2009','HEXACAMPEAO');
INSERT INTO USUARIO VALUES(NULL,'CHIRLENE','CHIRLENE2009','HEXACAMPEAO');
INSERT INTO USUARIO VALUES(NULL,'MARIANA','MARIANA2009','HEXAAAMPEAO');


SELECT * FROM USUARIO;

/*
+-----------+----------------+------------------+-------------+
| IDUSUARIO | NOME           | LOGIN            | SENHA       |
+-----------+----------------+------------------+-------------+
|         1 | ANDRADE        | ANDRADE2009      | HEXACAMPEAO |
|         2 | MARCOS         | MARCOS.2020      | 12458547aS@ |
|         3 | ADRIANO        | ADRIRADIOLOGISTA | ATOMY2021   |
|         4 | NEIDEFFERREIRA | ANDRADE2009      | HEXACAMPEAO |
|         5 | LAURA_BEE      | LAURA_BEE        | 4975DFHJID  |
|         6 | SANDRO         | SANDRO2009       | HEXACAMPEAO |
|         7 | ROBERVAL       | ROBERVAL2009     | HEXACAMPEAO |
|         8 | ADRENALINA     | ADRENALINA2009   | HEXACAMPEAO |
|         9 | CHIRLENE       | CHIRLENE2009     | HEXACAMPEAO |
|        10 | MARIANA        | MARIANA2009      | HEXAAAMPEAO |
+-----------+----------------+------------------+-------------+
*/
