
-- INSERINDO OS REGISTROS NOVOS ---------------------------------------------------

INSERT INTO RELATORIO_LOCADORA
SELECT L.IDLOCACAO, F.NOME AS "FILME", G.NOME AS "GENERO", L.DATA AS "DATA", L.DIAS AS "DIA", L.MIDIA AS "MIDIA"
FROM GENERO G
INNER JOIN FILME F 
ON G.IDGENERO = F.ID_GENERO
INNER JOIN LOCACAO L 
ON L.ID_FILME = F.IDFILME
WHERE IDLOCACAO NOT IN (SELECT IDLOCACAO FROM RELATORIO_LOCADORA);

/*
INSERT 0 0

Query returned successfully in 335 msec.
*/
