
-- CRIANDO UM PROCEDIMENTO(PROCEDURE) ANÔNIMO COLETIVA

CREATE OR REPLACE PROCEDURE BONUS(P_IDALUNO ALUNO.IDALUNO%TYPE, P_PERCENT NUMBER)
AS 
	BEGIN
		UPDATE ALUNO SET SALARIO = SALARIO + (SALARIO * (P_PERCENT / 100))
		WHERE P_IDALUNO = P_IDALUNO;
	END;
/

/*
Procedure BONUS compilado
*/


-- CRIANDO UM PROCEDIMENTO(PROCEDURE) ANÔNIMO INDIVIDUAL

CREATE OR REPLACE PROCEDURE AUMENTO(P_IDALUNO ALUNO.IDALUNO%TYPE, P_PERCENT NUMBER)
AS 
	BEGIN
		UPDATE ALUNO SET SALARIO = SALARIO + (SALARIO * (P_PERCENT / 100))
		WHERE P_IDALUNO = ALUNO.IDALUNO;
	END;
/

/*
Procedure AUMENTO compilado
*/


-- PRIMEIRO ETAPA: CRIA UM PROCEDIMENTO PARA QUE POSSA ENTRAR EM AÇÃO CASO SEJA CHAMADO

CREATE OR REPLACE PROCEDURE LOGPROC IS
BEGIN
	INSERT INTO AUDITORIA(DATA_LOGIN,LOGIN) VALUES(SYSDATE,USER);
END LOGPROC;
/

/*
Procedure LOGPROC compilado
*/

