
-- AS TRIGGERS DEVEM TER O TAMANHO MAXIMO DE 32K.
-- NÃO EXECUTAM COMANDOS DE DTL - COMMIT, ROLLBACK E SAVEPOINTS.


-- TRIGGER ERRADA - VALIDANDO O AUMENTO DO SALÁRIO

CREATE OR REPLACE TRIGGER CHECK_SALARIO
BEFORE INSERT OR UPDATE ON ALUNO  
FOR EACH ROW
BEGIN
	IF :NEW.SALARIO < 2000 THEN
		RAISE_APPLICATION_ERROR(-2000, 'VALOR INCORRETO')
	END IF;
END;
/

/*
Trigger CHECK_SALARIO compilado

LINE/COL  ERROR
--------- -------------------------------------------------------------
4/2       PLS-00103: Encontrado o símbolo "END" quando um dos seguintes símbolos era esperado:     := . ( % ; O símbolo ";" foi substituído por "END" para continuar. 
Erros: verifique o log do compilador
*/



-- TRIGGER CORRETA - VALIDANDO O AUMENTO DO SALÁRIO

CREATE OR REPLACE TRIGGER CHECK_SALARIO
BEFORE INSERT OR UPDATE ON ALUNO  
FOR EACH ROW
BEGIN
	IF :NEW.SALARIO < 2000 THEN
		RAISE_APPLICATION_ERROR(-2000, 'VALOR INCORRETO');
	END IF;
END;
/

/*
Trigger CHECK_SALARIO compilado
*/



-- TRIGGER DE EVENTOS ------------------------------------------------------------


-- SEGUNDA ETAPA: CRIA UM GATILHO OU SINAL PARA QUE POSSA CHAMAR UMA AÇÃO SE
-- O SINAL OU GATILHO SEJA DADO.

CREATE OR REPLACE TRIGGER LOGTRIGGER
AFTER LOGON ON DATABASE
CALL LOGPROC
/

/*
Trigger LOGTRIGGER compilado
*/


CREATE OR REPLACE TRIGGER FALHA_LOGON
AFTER SERVERERROR
ON DATABASE
BEGIN
  IF (IS_SERVERERROR(1017)) THEN
    INSERT INTO AUDITORIA(DATA_LOGIN,LOGIN) 
    VALUES(SYSDATE,'ORA-1017');
  END IF;
END FALHA_LOGON;
/



-- FAZENDO BECKUP DOS REGISTROS ANTES DE SER DELETADO USANDO TRIGGERS --------------

CREATE OR REPLACE TRIGGER LOG_USUARIO
BEFORE DELETE ON USUARIOS
FOR EACH ROW
BEGIN
	INSERT INTO BKP_USER VALUES(:OLD.IDUSUARIO,:OLD.NOME,:OLD.EMAIL,:OLD.SALARIO);
END;
/

/*
Trigger LOG_USUARIO compilado
*/
