
-- CONSULTANDO AS INFORMAÇÕES DA TABLESPACE

SELECT TABLESPACE_NAME, FILE_NAME
FROM DBA_DATA_FILES;

/*
TABLESPACE FILE_NAME                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
---------- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
USERS      C:\ORACLEXE\APP\ORACLE\ORADATA\XE\USERS.DBF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
SYSAUX     C:\ORACLEXE\APP\ORACLE\ORADATA\XE\SYSAUX.DBF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
UNDOTBS1   C:\ORACLEXE\APP\ORACLE\ORADATA\XE\UNDOTBS1.DBF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
SYSTEM     C:\ORACLEXE\APP\ORACLE\ORADATA\XE\SYSTEM.DBF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
RECURSOS_H C:\DATA\RH_01.DBF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
UMANOS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

RECURSOS_H C:\DATA\RH_02.DBF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
UMANOS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

RECURSOS_H C:\DATA\RH_03.DBF                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

TABLESPACE FILE_NAME                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
---------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
UMANOS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     

7 linhas selecionadas. 
*/
