
-- INSERINDO DADOS NA TABELA

INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Joao Marcelo');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Mariana Santos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Carlos Eduardo');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Adriano Santos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Neide Ferreira');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Laura Beatriz');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Maria Ester');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Sergio Fonseca');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Rubens Prado');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Maria Jose');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Carla Balbino');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Cristovao Ramos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Beatriz Ramos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Diego Balbino');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Maria da Graças');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Cristiane Brota');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Messias Bolsonaro');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Joao Carlos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Raulino Galvao');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Mayara Barbosa');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Cassius Gama');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Karla Geovanne');
