SELECT TABLESPACE_NAME, FILE_NAME
FROM DBA_DATA_FILES;

CREATE SEQUENCE SEQ_GERAL
START WITH 100
INCREMENT BY 10;

CREATE TABLE FUNCIONARIOS(
	IDFUNCIONARIO INT PRIMARY KEY,
	NOME VARCHAR2(30)
)TABLESPACE RECURSOS_HUMANOS;


INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Joao Marcelo');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Mariana Santos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Carlos Eduardo');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Adriano Santos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Neide Ferreira');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Laura Beatriz');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Maria Ester');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Sergio Fonseca');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Rubens Prado');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Maria Jose');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Carla Balbino');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Cristovao Ramos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Beatriz Ramos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Diego Balbino');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Maria da Graças');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Cristiane Brota');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Messias Bolsonaro');

INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Joao Carlos');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Raulino Galvao');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Mayara Barbosa');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Cassius Gama');
INSERT INTO FUNCIONARIOS VALUES(SEQ_GERAL.NEXTVAL, 'Karla Geovanne');

DELETE FROM FUNCIONARIOS
WHERE IDFUNCIONARIO = 470;

SELECT IDFUNCIONARIO ,NOME FROM FUNCIONARIOS;

DROP SEQUENCE SEQ_GERAL;

DELETE FROM FUNCIONARIOS;