-- CREATING THE STUDENT TABLE.

CREATE TABLE ALUNO(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO


-- CREATING THE ADDRESS TABLE WITH THE 1 X 1 REALIZATION.

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL CHECK (UF IN('RJ','SP','MG')),
	ID_ALUNO INT UNIQUE
)
GO 


-- CREATING THE TELEPHONE TABLE WITH THE 1 X N REALIZATION.

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK (TIPO IN ('RES','COM','CEL')),
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT 
)
GO  

-------------------------------------------------------

-- CREATING THE TABLES ALREADY WITH THE RESTRICTIONS.

CREATE TABLE ALUNO(
	IDALUNO INT IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	EMAIL VARCHAR(50),
	NASCIMENTO DATE NOT NULL,
	CONSTRAINT PK_IDALUNO PRIMARY KEY(IDALUNO),
	CONSTRAINT UNIQUE_EMAIL UNIQUE (EMAIL),
	CONSTRAINT CHECK_SEXO CHECK (SEXO IN ('M','F'))
)
GO 


CREATE TABLE ENDERECO(
	IDENDERECO INT IDENTITY,
	RUA VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	UF CHAR(2) NOT NULL,
	ID_ALUNO INT,
	CONSTRAINT PK_ENDERECO PRIMARY KEY (IDENDERECO),
	CONSTRAINT UNIQUE_ID_ALUNO UNIQUE (ID_ALUNO),
	CONSTRAINT FK_ENDERECO_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (IDALUNO)
)
GO  


CREATE TABLE TELEFONE(
	IDTELEFONE INT IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT,
	CONSTRAINT PK_TELEFONE PRIMARY KEY (IDTELEFONE),
	CONSTRAINT CHECK_TIPO CHECK (TIPO IN ('COM','RES','CEL')),
	CONSTRAINT FK_TELEFONE_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (IDALUNO)
)
GO 
