-- Inserindo dados na tabela CARRO.

INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'UNO','BBJ-8495',NULL); -- FIAT - ok
INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'ARGO','XIA-1137',NULL); -- FIAT - ok
INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'GOL','GHO-3187',NULL); -- VOLKSWAGEN - ok
INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'COROLA','NNN-8711',NULL); -- TOYOTA - ok
INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'FUSION','XXX-6666',NULL); -- FORD - ok
INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'MARCH','IYQ-7943',NULL); -- NISSAN - ok
INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'CRONOS','GTB-7780',NULL); -- FIAT - ok
INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'CAMRY','AFT-6973',NULL); -- TOYOTA - ok
INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'KA','CUU-2424',NULL); -- FORD - ok
INSERT INTO CARRO(IDCARRO,MODELO,PLACA,ID_MARCA) VALUES(NULL,'VERSA','ROL-8006',NULL); -- NISSAN - ok

-- Verificando se os dados estão realmente na tabela CARRO.

SELECT * FROM CARRO;

/*
+---------+--------+----------+----------+
| IDCARRO | MODELO | PLACA    | ID_MARCA |
+---------+--------+----------+----------+
|       2 | UNO    | BBJ-8495 |     NULL |
|       3 | ARGO   | XIA-1137 |     NULL |
|       4 | GOL    | GHO-3187 |     NULL |
|       5 | COROLA | NNN-8711 |     NULL |
|       6 | FUSION | XXX-6666 |     NULL |
|       7 | MARCH  | IYQ-7943 |     NULL |
|       8 | CRONOS | GTB-7780 |     NULL |
|       9 | CAMRY  | AFT-6973 |     NULL |
|      10 | KA     | CUU-2424 |     NULL |
|      11 | VERSA  | ROL-8006 |     NULL |
+---------+--------+----------+----------+
*/

-- Inserindo dados na tabela MARCA.

INSERT INTO MARCA(IDMARCA,MARCA) VALUES(NULL,'FIAT');
INSERT INTO MARCA(IDMARCA,MARCA) VALUES(NULL,'VOLKSWAGEN');
INSERT INTO MARCA(IDMARCA,MARCA) VALUES(NULL,'TOYOTA');
INSERT INTO MARCA(IDMARCA,MARCA) VALUES(NULL,'FORD');
INSERT INTO MARCA(IDMARCA,MARCA) VALUES(NULL,'NISSAN');

-- Verificando se os dados estão realmente na tabela MARCA.

SELECT * FROM MARCA;

/*
+---------+------------+
| IDMARCA | MARCA      |
+---------+------------+
|       1 | FIAT       |
|       4 | FORD       |
|       5 | NISSAN     |
|       3 | TOYOTA     |
|       2 | VOLKSWAGEN |
+---------+------------+
*/

-- Inserindo dados na tabela COR.

INSERT INTO COR(IDCOR,COR) VALUES(NULL,'PRETO');
INSERT INTO COR(IDCOR,COR) VALUES(NULL,'CINZA');
INSERT INTO COR(IDCOR,COR) VALUES(NULL,'BRANCO');
INSERT INTO COR(IDCOR,COR) VALUES(NULL,'VERMELHO');
INSERT INTO COR(IDCOR,COR) VALUES(NULL,'VERDE');
INSERT INTO COR(IDCOR,COR) VALUES(NULL,'AZUL');
INSERT INTO COR(IDCOR,COR) VALUES(NULL,'AMARELO');
INSERT INTO COR(IDCOR,COR) VALUES(NULL,'LARANJA');
INSERT INTO COR(IDCOR,COR) VALUES(NULL,'ANIL');
INSERT INTO COR(IDCOR,COR) VALUES(NULL,'VIOLETA');

-- Verificando se os dados estão realmente na tabela COR.

SELECT * FROM COR;

/*
+-------+----------+
| IDCOR | COR      |
+-------+----------+
|     7 | AMARELO  |
|     9 | ANIL     |
|     6 | AZUL     |
|     3 | BRANCO   |
|     2 | CINZA    |
|     8 | LARANJA  |
|     1 | PRETO    |
|     5 | VERDE    |
|     4 | VERMELHO |
|    10 | VIOLETA  |
+-------+----------+
*/

-- Inserindo dados na tabela CARRO_COR.

INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(2,3);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(2,1);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(3,3);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(3,1);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(4,1);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(5,2);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(6,4);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(6,1);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(7,5);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(7,1);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(8,8);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(8,1);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(9,10);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(10,1);
INSERT INTO CARRO_COR(ID_CARRO,ID_COR) VALUES(10,9);

-- Verificando se os dados estão realmente na tabela CARRO_COR.

SELECT * FROM CARRO_COR;

/*
+----------+--------+
| ID_CARRO | ID_COR |
+----------+--------+
|        2 |      1 |
|        3 |      1 |
|        4 |      1 |
|        6 |      1 |
|        7 |      1 |
|        8 |      1 |
|       10 |      1 |
|        5 |      2 |
|        2 |      3 |
|        3 |      3 |
|        6 |      4 |
|        7 |      5 |
|        8 |      8 |
|       10 |      9 |
|        9 |     10 |
+----------+--------+
*/

-- Inserindo dados na tabela CLIENTE.

INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'NEIDE FERREIRA','F',2);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'LAURA BEATRIZ','F',3);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'MARCOS GONZAGA','M',4);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'BRUNA LIMA','F',5);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'MARIA JOSÉ','F',6);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'CARLOS PEREIRA','M',7);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'DANIEL AMARAL','M',8);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'GABRIEL PASSOS','M',9);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'MAURICIO PEREIRA','M',10);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ID_CARRO) VALUES(NULL,'GABRIELA CAMRY','F',11);

-- Verificando se os dados estão realmente na tabela CLIENTE.

SELECT * FROM CLIENTE;

/*
+-----------+------------------+------+----------+
| IDCLIENTE | NOME             | SEXO | ID_CARRO |
+-----------+------------------+------+----------+
|         1 | NEIDE FERREIRA   | F    |        2 |
|         2 | LAURA BEATRIZ    | F    |        3 |
|         3 | MARCOS GONZAGA   | M    |        4 |
|         4 | BRUNA LIMA       | F    |        5 |
|         5 | MARIA JOSÉ       | F    |        6 |
|         6 | CARLOS PEREIRA   | M    |        7 |
|         7 | DANIEL AMARAL    | M    |        8 |
|         8 | GABRIEL PASSOS   | M    |        9 |
|         9 | MAURICIO PEREIRA | M    |       10 |
|        10 | GABRIELA CAMRY   | F    |       11 |
+-----------+------------------+------+----------+
*/

-- Inserindo dados na tabela TELEFONE.

INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'CEL','79998960514',1);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'RES','7932548547',1);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'CEL','79978560514',2);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'CEL','79978960514',3);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'COM','7932514578',5);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'CEL','79998000514',5);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'CEL','79998369514',6);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'RES','7932784512',6);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'CEL','79977960514',7);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'COM','7932564578',7);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'CEL','79994578514',8);
INSERT INTO TELEFONE(IDTELEFONE,TIPO,NUMERO,ID_CLIENTE) VALUES(NULL,'CEL','79998999914',9);

-- Verificando se os dados estão realmente na tabela TELEFONE.

SELECT * FROM TELEFONE;

/*
+------------+------+-------------+------------+
| IDTELEFONE | TIPO | NUMERO      | ID_CLIENTE |
+------------+------+-------------+------------+
|          1 | CEL  | 79998960514 |          1 |
|          2 | RES  | 7932548547  |          1 |
|          3 | CEL  | 79978560514 |          2 |
|          4 | CEL  | 79978960514 |          3 |
|          5 | COM  | 7932514578  |          5 |
|          6 | CEL  | 79998000514 |          5 |
|          7 | CEL  | 79998369514 |          6 |
|          8 | RES  | 7932784512  |          6 |
|          9 | CEL  | 79977960514 |          7 |
|         10 | COM  | 7932564578  |          7 |
|         11 | CEL  | 79994578514 |          8 |
|         12 | CEL  | 79998999914 |          9 |
+------------+------+-------------+------------+
*/
