-- VERIFICANDO AS CHAVES E OUTROS DETALHES

SHOW CREATE TABLE PESSOA;

/*
| PESSOA | CREATE TABLE `pessoa` (
  `COLUNA1` varchar(30) DEFAULT NULL,
  `COLUNA2` date NOT NULL,
  `COLUNA3` varchar(30) DEFAULT NULL,
  `COLUNA4` varchar(30) NOT NULL,
  `COLUNA` varchar(30) DEFAULT NULL,
  `COLUNA100` int DEFAULT NULL,
  UNIQUE KEY `COLUNA4` (`COLUNA4`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/

SHOW CREATE TABLE TIME;

/*
| TIME  | CREATE TABLE `time` (
  `IDTIME` int NOT NULL AUTO_INCREMENT,
  `TIME` varchar(30) DEFAULT NULL,
  `ID_PESSOA` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`IDTIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/