
-- INSERINDO DADOS NA TABELA

INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Moda Primavera');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Moda Verão');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Moda Inverno');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Moda Social');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Saúde e Bem Estar');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Cama e Banho');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Crédito Social');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Volta as Aulas');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Semana Santa');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Moda Esportiva');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Moda Evangelica');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Outlet');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Perfumaria');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Moda Infantil');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Copa do Mundo');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Não ao Racismo');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Preconceito');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Homofobia');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Cêncer de Mama');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Criança Feliz');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Moda Práia');
INSERT INTO CAMPANHAS VALUES(SEQ_GERAL.NEXTVAL, 'Natal');
