-- CREATING THE STUDENT TABLE.

CREATE TABLE ALUNO(
	IDALUNO INT IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
)
GO 

-- CREATING PRIMARY KEY ON IDALUNO COLUMN.

ALTER TABLE ALUNO 
ADD CONSTRAINT PK_IDALUNO 
PRIMARY KEY (IDALUNO)
GO 

-- CREATING THE CHECK RELATIONSHIP BETWEEN STUDENT AND SEX.

ALTER TABLE ALUNO 
ADD CONSTRAINT CK_SEXO 
CHECK (SEXO IN ('M','F'))
GO 

-- DESCRIPTION COMMANDS.
-- PROCEDURES - COMMANDS CREATED AND STORED ALREADY IN THE SQL SERVER SYSTEM.

SP_COLUMNS ALUNO
GO 

SP_HELP ALUNO
GO 
