/* Modelagem Básica - 

ENTIDADE = TABELA
CAMPOS = ATRIBUTOS */

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - ENDERECO(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO DE DADOS

/* INICIANDO A MODELAGEM FÍSICA */
/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTE */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF CHAR(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
	
	);
	
/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* FORMA 01 - OMITINDO AS COLUNAS */

INSERT INTO CLIENTE VALUE('JOAO','M','JOAO@GMAIL.COM',988368273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUE('CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUE('JORGE','M',NULL,988368273,'22923110','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS - "MELHOR ALTERNATIVA"*/ 

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('ADRIANO','M','SENADOR SOARES - TIJUCA - RIO DE JANEIRO -RJ','998960414',887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLIENTE VALUES('ANA','F','ANA@GMAIL.COM',85548960,'48756695182','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          ('CARLA','F','CARLA@TERRA.COM.BR',774582870,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');
						 
/* O COMANDO SELECT - SELEÇÃO, PROJEÇÃO E JUNÇÃO */

SELECT NOW();
SELECT NOW() as DATA_HORA, 'ADRIANO SANTOS' AS PROFESSOR;		
SELECT 'ADRIANO SANTOS';
SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */	

SELECT NOME, SEXO, EMAIL FROM CLIENTE;
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;

/* TABELA PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* TABELA ERRADA - NÃO DIGITE DIRETAMENTE NO BANCO */

CLEATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30)
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),
); 	

/*
PARA FAZER PROJEÇÃO, USA-SE O COMANDO 'SELECT'
PARA FAZER SELECÇÃO, USA-SE O COMANDO 'WHERE'
*/				 
	
/* FILTRANDO DADOS COM WHERE E LIKE */	

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

/* UTILIZANDO O LIKE */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA 
LINHA DE COMANDO CORRETA */ 

SELECT NOME, SEXO FROM CLIENTE 
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';

/* LOGICA DOS PREDICADOS - OPERADORES LÓGICOS:

OR -> PARA QUE A SAÍDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDICAO SEJA VERDADEIRA.
AND -> PARA QUE A SAÍDA SEJA VERDADEIRA, TODAS AS CONDICOES PRECISAM SER VERDADEIRA.
 */
 
 SHOW DATABASES;
 
 USE PROJETO;
  
 SELECT * FROM CLIENTE;
 
 /* OR - OU -> FILTRAGEM MAIS GENERALIZADA */
 
 SELECT NOME, SEXO, ENDERECO FROM CLIENTE
 WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';
 
 SELECT NOME, SEXO, ENDERECO FROM CLIENTE
 WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';
 
 /* AND - E -> FILTRAGEM MAIS RESTRITA */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/* COUNT(*), GROUP BY - PERFORMANCE COM OPERADORES LOGICOS */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) FROM CLIENTE;
SELECT COUNT(*) AS 'Quantidade de Registro da Tab. Cliente' FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

/* VAMOS SUPOR QUE NA TABELA CLIENTE TENHA 1 MILAO DE REGISTROS */

SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY CIDADE;

/* TEMOS A SEGUINTE CONDICAO: 
SEXO = F  
CIDADE = RIO DE JANEIRO */

/* TRATANDO A CONDICAO COM: OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR CIDADE = 'RIO DE JANEIRO';

/* TRATANDO A CONDICAO COM: E / AND
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR CIDADE = 'RIO DE JANEIRO';

/* MAIS ALGUNS COMANDOS BASICOS - FILTRANDO VALORES NULOS -------------------------------------------------- */

/* Obs.: NUNCA utilize o sinal de = par filtrar valores nulos, pois isso não sabemos o que um valor NULL é. */

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE sexo = 'F';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL = NULL;

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;


/* MAIS ALGUNS COMANDOS BASICOS - UTILIZANDO O UPDATE PARA ATUALIZAR VALORES ----------------- */

/* Obs.: Use sempre um SELECT antes do UPDATE para confirmar se o dado é mesmo o dado correto a ser atualizado. */

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT NOME, EMAIL
FROM CLIENTE;

/* WHERE - VAI SER O SEU MELHOR AMIGO DA VIDA
PRA VIDA INTEIRA */


SELECT * FROM CLIENTE
WHERE NOME = 'LILIAN';

UPDATE CLIENTE
SET EMAIL = 'JOAOA@IG.COM.BR'
WHERE NOME = 'JOAO';

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'adrianosantos.git@hotmail.com'
WHERE NOME = 'ADRIANO';

SELECT NOME, EMAIL
FROM CLIENTE;


/*COMMIT E ROLLBACK */

/* MAIS ALGUNS COMANDOS BASICOS - DELETANDO REGISTROS COM A CLAUSULA DELETE ------------------------ */

/* Obs 1.: Cuidado ao utilizar a clausula DELETE. Faca sempre um SELECT para conferir os dados. */
/* Obs 2.: Nunca se esqueça do WHERE ao utilizar o DELETE. Na maioria  dos casos, filtrar é necessario.*/

DELETE FROM CLIENTE; -- Nunca use esse comando sem antes seguir os seguntes passos:

SELECT * FROM CLIENTE WHERE NOME = 'ANA';

SELECT COUNT(*) FROM CLIENTE; -- TOTAL 6

SELECT COUNT(*) FROM CLIENTE WHERE NOME = 'ANA'; -- TOTAL A SER DELETADO SERA 1 CHAMADO 'ANA'

DELETE FROM CLIENTE WHERE NOME = 'ANA'; -- CLIENTE DELETADO CORRETAMENTE

SELECT COUNT(*) FROM CLIENTE; -- RESTANDO APENAS 5

INSERT INTO CLIENTE VALUES('CARLA','F','c.lopes@uol.com', '45638854', '784599658','RUA COPPER LEAF - WILLIAMSBURG - KITCHENER');

-- ATENCAO PARA ESSAS SUPER DICAS A SEGUIR:

-- Por que está ERRADO? Por que DELETA alem do que foi pedido, como mostrado nessa projecao.
-- OR traz todo mundo com pelo menos uma das duas condicoes.
SELECT * FROM CLIENTE WHERE NOME = 'CARLA' OR EMAIL = 'carla@terra.com.br'; 
DELETE FROM CLIENTE WHERE NOME = 'CARLA' OR EMAIL = 'carla@terra.com.br';

-- Por que está CORRETO? Por que DELETA SOMENTE o que foi pedido, como mostrado nessa projecao.
-- AND traz APENAS o registro que satisfaca as duas condicoes.
SELECT * FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'carla@terra.com.br'; 
DELETE FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'carla@terra.com.br'; 



