/* LOGICA DOS PREDICADOS - OPERADORES LÓGICOS:

OR -> PARA QUE A SAÍDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDICAO SEJA VERDADEIRA.
AND -> PARA QUE A SAÍDA SEJA VERDADEIRA, TODAS AS CONDICOES PRECISAM SER VERDADEIRA.
 */
 
 SHOW DATABASES;
 
 USE PROJETO;
  
 SELECT * FROM CLIENTE;
 
 /* OR - OU -> FILTRAGEM MAIS GENERALIZADA */
 
 SELECT NOME, SEXO, ENDERECO FROM CLIENTE
 WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';
 
 SELECT NOME, SEXO, ENDERECO FROM CLIENTE
 WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';
 
 /* AND - E -> FILTRAGEM MAIS RESTRITA */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/* TEMOS A SEGUINTE CONDICAO: 
SEXO = F  
CIDADE = RIO DE JANEIRO */

/* TRATANDO A CONDICAO COM: OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR CIDADE = 'RIO DE JANEIRO';

/* TRATANDO A CONDICAO COM: E / AND
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR CIDADE = 'RIO DE JANEIRO';