/* COUNT(*), GROUP BY - PERFORMANCE COM OPERADORES LOGICOS */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) 
FROM CLIENTE;

SELECT COUNT(*) AS 'Quantidade de Registro da Tab. Cliente' 
FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*) 
FROM CLIENTE 
GROUP BY SEXO;

/* VAMOS SUPOR QUE NA TABELA CLIENTE TENHA 1 MILAO DE REGISTROS */

SELECT COUNT(*) 
FROM CLIENTE;

SELECT SEXO, COUNT(*) 
FROM CLIENTE 
GROUP BY CIDADE;
