/* MAIS ALGUNS COMANDOS BASICOS - UTILIZANDO O UPDATE PARA ATUALIZAR VALORES ----------------- */

/* Obs.: Use sempre um SELECT antes do UPDATE para confirmar se o dado é mesmo o dado correto a ser atualizado. */

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM';

SELECT NOME, EMAIL
FROM CLIENTE;

/* WHERE - VAI SER O SEU MELHOR AMIGO DA VIDA
PRA VIDA INTEIRA */


SELECT * FROM CLIENTE
WHERE NOME = 'LILIAN';

UPDATE CLIENTE
SET EMAIL = 'JOAOA@IG.COM.BR'
WHERE NOME = 'JOAO';

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'adrianosantos.git@hotmail.com'
WHERE NOME = 'ADRIANO';

SELECT NOME, EMAIL
FROM CLIENTE;
