
SELECT MAX(IDLOCACAO) AS "RELATORIO", (SELECT MAX(IDLOCACAO) FROM LOCACAO) AS "LOCACAO"
FROM RELATORIO_LOCADORA;

/*
31	31
*/


-- SELECT PARA TRAZER OS REGISTROS NOVOS

SELECT L.IDLOCACAO, F.NOME AS "FILME", G.NOME AS "GENERO", L.DATA AS "DATA", L.DIAS AS "DIA", L.MIDIA AS "MIDIA"
FROM GENERO G
INNER JOIN FILME F 
ON G.IDGENERO = F.ID_GENERO
INNER JOIN LOCACAO L 
ON L.ID_FILME = F.IDFILME
WHERE IDLOCACAO NOT IN (SELECT IDLOCACAO FROM RELATORIO_LOCADORA);

/*
Successfully run. Total query runtime: 227 msec.
0 rows affected.
*/
