/* O COMANDO SELECT - SELEÇÃO, PROJEÇÃO E JUNÇÃO */

SELECT NOW();
SELECT NOW() as DATA_HORA, 'ADRIANO SANTOS' AS PROFESSOR;		
SELECT 'ADRIANO SANTOS';
SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */	

SELECT NOME, SEXO, EMAIL FROM CLIENTE;
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM CLIENTE;

/* TABELA PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* TABELA ERRADA - NÃO DIGITE DIRETAMENTE NO BANCO */

CLEATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30)
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),
); 	

/*
PARA FAZER PROJEÇÃO, USA-SE O COMANDO 'SELECT'
PARA FAZER SELECÇÃO, USA-SE O COMANDO 'WHERE'
*/				 
	
/* FILTRANDO DADOS COM WHERE E LIKE */	

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

/* UTILIZANDO O LIKE */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA 
LINHA DE COMANDO CORRETA */ 

SELECT NOME, SEXO FROM CLIENTE 
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE 
WHERE ENDERECO LIKE 'OSCAR CURY%';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%CENTRO%';

/* LOGICA DOS PREDICADOS - OPERADORES LÓGICOS
OR -> PARA QUE A SAÍDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDICAO SEJA VERDADEIRA.
AND -> PARA QUE A SAÍDA SEJA VERDADEIRA, TODAS AS CONDICOES PRECISAM SER VERDADEIRA.
 */
 
 SHOW DATABASES;
 
 USE PROJETO;
  
 SELECT * FROM CLIENTE;
 
 /* OR - OU -> FILTRAGEM MAIS GENERALIZADA */
 
 SELECT NOME, SEXO, ENDERECO FROM CLIENTE
 WHERE SEXO = 'M' OR ENDERECO LIKE '%RJ';
 
 SELECT NOME, SEXO, ENDERECO FROM CLIENTE
 WHERE SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';
 
 /* AND - E -> FILTRAGEM MAIS RESTRITA */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE SEXO = 'F' AND ENDERECO LIKE '%ESTACIO';

/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LOGICOS */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) FROM CLIENTE;
SELECT COUNT(*) AS 'Quantidade de Registro da Tab. Cliente' FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

/* VAMOS SUPOR QUE NA TABELA CLIENTE TENHA 1 MILAO DE REGISTROS */

SELECT COUNT(*) FROM CLIENTE;

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY CIDADE;

/* TEMOS A SEGUINTE CONDICAO: 
SEXO = F  
CIDADE = RIO DE JANEIRO */

/* TRATANDO A CONDICAO COM: OU / OR
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR CIDADE = 'RIO DE JANEIRO';

/* TRATANDO A CONDICAO COM: E / AND
70% MULHERES = SEXO = F
30% MORA NO RIO DE JANEIRO */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE SEXO = 'F' OR CIDADE = 'RIO DE JANEIRO';