-- ANTES DE CRIAR ESSE ARQUIVO FÍSICO, DEVE-SE CRIAR UMA PASTA CHAMADA 'Data'
-- PARA GUARDAR OS ARQUIVOS FÍSICOS. ESSES ARQUIVOS IRÁ APONTAR PARA UMA TABLESSPACE,
-- QUE É UM ARQUIVO LÓGICO. E NESSAS TABLESPACES, SÃO GUARDADAS AS TABELAS CRIADAS
-- POSTERIORMENTE, PORÉM SÃO SABEMOS EM QUAIS DESSAS TABLESPACE SERÁ GUARDADA. 

CREATE TABLESPACE RECURSOS_HUMANOS
DATAFILE 'C:/Data/RH_01.DBF'
SIZE 100M AUTOEXTEND
ON NEXT 100M
MAXSIZE 4096M;

/* TABLESPACE RECURSOS_HUMANOS criado. */


ALTER TABLESPACE RECURSOS_HUMANOS
ADD DATAFILE 'C:/Data/RH_02.DBF'
SIZE 100M AUTOEXTEND
ON NEXT 100M
MAXSIZE 4096M;

/* TABLESPACE RECURSOS_HUMANOS alterado. */

ALTER TABLESPACE RECURSOS_HUMANOS
ADD DATAFILE 'C:/Data/RH_03.DBF'
SIZE 200M AUTOEXTEND
ON NEXT 200M
MAXSIZE 4096M;

/* TABLESPACE RECURSOS_HUMANOS alterado. */
