INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (1,'Abbie Cornish',1982,'Austrália','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (2,'Adam Sandler',1966,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (3,'Al Pacino',1940,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (4,'Amy Adams',1974,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (5,'Andrea Riseborough',1981,'Reino Unido','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (6,'Anjelica Huston',1951,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (7,'Annasophia Robb',1993,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (8,'Anne Hathaway',1982,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (9,'Anthony Hopkins',1937,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (10,'Barkhad Abdi',1985,'Somália','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (11,'Barry Pepper',1970,'Canadá','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (12,'Benicio Del Toro',1967,'Porto Rico','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (13,'Bette Midler',1945,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (14,'Bill Nighy',1949,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (15,'Bridget Moynahan',1971,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (16,'Bruce Dern',1936,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (17,'Bruce McGill',1950,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (18,'Bryce Dallas Howard',1981,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (19,'Carice van Houten',1976,'Holanda','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (20,'Cate Blanchett',1969,'Austrália','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (21,'Catherine Keener',1959,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (22,'Channing Tatum',1980,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (23,'Charlize Theron',1975,'África do Sul','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (24,'Chris Cooper',1951,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (25,'Christian Bale',1974,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (26,'Christina Ricci',1980,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (27,'Christoph Waltz',1956,'Áustria','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (28,'Ciaran Hinds',1953,'Irlanda do Norte','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (29,'Colin Farrell',1976,'Irlanda','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (30,'Colin Firth',1960,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (31,'Daniel Craig',1968,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (32,'Daniel Radcliffe',1989,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (33,'Denzel Washington',1954,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (34,'Diane Keaton',1946,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (35,'Donald Sutherland',1935,'Canadá','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (36,'Eddie Murphy',1961,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (37,'Eddie Redmayne',1982,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (38,'Ed Harris',1950,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (39,'Edward Norton',1969,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (40,'Elijah Wood',1981,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (41,'Emma Stone',1988,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (42,'Emma Watson',1990,'Reino Unido','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (43,'Ethan Hawke',1970,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (44,'Fernando Tielve',1986,'Espanha','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (45,'Frances McDormand',1957,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (46,'Freddie Highmore',1992,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (47,'Gene Hackman',1930,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (48,'Geoffrey Rush',1951,'Austrália','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (49,'George Clooney',1961,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (50,'Gwyneth Paltrow',1972,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (51,'Haley Joel Osment',1988,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (52,'Halle Berry',1966,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (53,'Harrison Ford',1942,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (54,'Heath Ledger',1979,'Austrália','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (55,'Hector Bordoni',1965,'Argentina','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (56,'Helen Hunt',1963,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (57,'Helen Mirren',1945,'Reino Unido','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (58,'Hugh Grant',1960,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (59,'Hugh Jackman',1968,'Austrália','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (60,'Hugo Weaving',1960,'Austrália','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (61,'Ian McKellen',1939,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (62,'Irene Escolar',1988,'Espanha','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (63,'Jack Nicholson',1937,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (64,'Jamie Foxx',1967,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (65,'Javier Bardem',1969,'Espanha','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (66,'Jennifer Garner',1972,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (67,'Jennifer Lawrence',1990,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (68,'Jennifer Lopez',1969,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (69,'Jeremy Northam',1961,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (70,'Jesse Eisenberg',1983,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (71,'Jim Broadbent',1949,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (72,'John Cusack',1966,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (73,'John Hawkes',1959,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (74,'John Malkovich',1953,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (75,'John Travolta',1954,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (76,'Josh Brolin',1968,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (77,'Josh Hutcherson',1992,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (78,'Julie Christie',1940,'Reino Unido','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (79,'Kate Hudson',1979,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (80,'Katie Holmes',1978,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (81,'Keanu Reeves',1964,'Canadá','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (82,'Kerry Washington',1977,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (83,'Kevin Breznahan',1968,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (84,'Kristen Bell',1980,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (85,'Leonardo DiCaprio',1974,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (86,'Liam Hemsworth',1990,'Austrália','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (87,'Liam Neeson',1952,'Irlanda do Norte','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (88,'Lisa Kudrow',1963,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (89,'Liv Tyler',1977,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (90,'Maggie Gyllenhaal',1977,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (91,'Marcia Gay Harden',1959,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (92,'Marisa Tomei',1964,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (93,'Mark Wahlberg',1971,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (94,'Maryam Karimi',1980,'Afeganistão','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (95,'Matt Dillon',1964,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (96,'Matthew McConaughey',1969,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (97,'Mel Gibson',1956,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (98,'Michael Caine',1933,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (99,'Michael Pena',1976,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (100,'Mohamad Dolati',1989,'Bahrein','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (101,'Naomi Watts',1968,'Reino Unido','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (102,'Natalie Portman',1981,'Israel','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (103,'Natasha Richardson',1963,'Reino Unido','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (104,'Nick Stahl',1979,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (105,'Nicolas Cage',1964,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (106,'Nicole Kidman',1967,'Austrália','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (107,'Patrick Swayze',1952,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (108,'Patrick Wilson',1973,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (109,'Patton Oswalt',1969,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (110,'Paul Reiser',1956,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (111,'Philip Seymour Hoffman',1967,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (112,'Rachel McAdams',1978,'Canadá','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (113,'Rachel Roberts',1927,'Reino Unido','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (114,'Ray Romano',1957,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (115,'Regina King',1971,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (116,'Renee Zellweger',1969,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (117,'Rene Russo',1954,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (118,'Richard Gere',1949,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (119,'Robert De Niro',1943,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (120,'Robert Duvall',1931,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (121,'Robert Redford',1936,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (122,'Robin Williams',1951,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (123,'Rupert Grint',1988,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (124,'Sam Riley',1980,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (125,'Sandra Bullock',1964,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (126,'Sarah Jessica Parker',1965,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (127,'Scarlett Johansson',1984,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (128,'Scott Cohen',1961,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (129,'Scott Glenn',1939,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (130,'Sean Bean',1959,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (131,'Sean Penn',1960,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (132,'Shia LaBeouf',1986,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (133,'Shohreh Aghdashloo',1952,'Irã','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (134,'Stephen Rea',1946,'Irlanda','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (135,'Susan Sarandon',1946,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (136,'Tom Hanks',1956,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (137,'Tommy Lee Jones',1946,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (138,'Tom Wilkinson',1948,'Reino Unido','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (139,'Vanessa Hudgens',1988,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (140,'Viggo Mortensen',1958,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (141,'Viola Davis',1965,'EUA','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (142,'Violante Placido',1976,'Itália','feminino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (143,'will.i.am',1975,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (144,'William H. Macy',1950,'EUA','masculino');
INSERT INTO atores (`id_ator`,`nome_ator`,`ano_nascimento`,`nacionalidade`,`sexo`) VALUES (145,'Zooey Deschanel',1980,'EUA','feminino');
