INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (1,'Que mulher é essa?','Comédia',93,2001,2.09);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (2,'A Senha','Drama',99,2001,2.19);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (3,'Do que as mulheres gostam','Comédia',127,2001,2.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (4,'Dia de Treinamento','Drama',122,2001,1.79);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (5,'O Senhor dos Anéis: A sociedade do anel','Ficção e Fantasia',178,2001,2.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (6,'Harry Potter e a Pedra Filosofal','Ficção e Fantasia',152,2001,2.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (7,'Os Excêntricos Tenenbaums','Comédia',110,2002,1.89);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (8,'Seu marido e minha mulher','Comédia',91,2002,2.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (9,'11 de setembro','Drama',134,2002,2.99);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (10,'Simone','Drama',117,2002,2.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (11,'É hora do show','Comédia',95,2002,1.79);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (12,'O Senhor dos Anéis: As duas torres','Ficção e Fantasia',179,2002,2.39);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (13,'Harry Potter e a Câmara Secreta','Ficção e Fantasia',161,2002,1.79);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (14,'O Novato','Mistério e Suspense',115,2003,1.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (15,'Alguém tem que ceder','Comédia',128,2003,1.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (16,'A última noite','Drama',135,2003,1.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (17,'Revelações','Mistério e Suspense',106,2003,1.99);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (18,'Lições Para Toda a Vida','Drama',111,2003,1.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (19,'21 gramas','Drama',124,2003,2.09);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (20,'Simplesmente amor','Comédia',135,2003,2.29);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (21,'O Senhor dos Anéis: O retorno do rei','Ficção e Fantasia',200,2003,1.99);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (22,'Visões','Arte',107,2004,2.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (23,'Dança comigo','Drama',106,2004,1.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (24,'Uma Eleição Muito Atrapalhada','Comédia',110,2004,2.89);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (25,'Bridget Jones: No Limite da Razão','Drama',108,2004,2.89);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (26,'Ray','Drama',152,2004,2.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (27,'Monster - Desejo Assassino','Drama',109,2004,2.09);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (28,'Harry Potter e o Prisioneiro de Azkabam','Ficção e Fantasia',142,2004,1.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (29,'Tudo por Dinheiro','Drama',122,2005,2.79);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (30,'Capote','Drama',114,2005,2.39);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (31,'Harry Potter e o Cálice de Fogo','Ficção e Fantasia',157,2005,2.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (32,'Falsária','Drama',93,2006,2.89);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (33,'V de Vingança','Drama',132,2006,1.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (34,'Armações do Amor','Drama',97,2006,1.99);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (35,'Happy Feet','Animação',108,2006,1.79);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (36,'As Torres Gêmeas','Drama',129,2006,1.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (37,'Candy','Drama',116,2006,1.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (38,'A casa do lago','Drama',99,2006,2.49);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (39,'Não estou lá','Drama',135,2007,1.79);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (40,'Quando Me Apaixono','Drama',100,2007,1.99);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (41,'O Reino','Drama',110,2007,2.09);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (42,'Onde os Fracos Não Têm Vez','Drama',122,2007,1.49);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (43,'Invasores','Mistério e Suspense',99,2007,2.09);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (44,'Harry Potter e a Ordem da Fênix','Ficção e Fantasia',138,2007,2.49);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (45,'Queime Depois de Ler','Drama',96,2008,2.39);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (46,'Sleepwalking','Drama',101,2008,1.79);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (47,'Um Amor de Tesouro','Ação e Aventura',112,2008,2.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (48,'Astro Boy','Ação e Aventura',94,2009,2.89);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (49,'Harry Potter e o Enigma do Príncipe','Ficção e Fantasia',153,2009,1.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (50,'Inverno da Alma','Drama',100,2010,2.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (51,'Uma Manhã Gloriosa','Comédia',107,2010,2.99);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (52,'Jogo de Poder','Drama',108,2010,2.89);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (53,'O Vencedor','Ação e Aventura',116,2010,2.49);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (54,'Harry Potter e as Relíquias da Morte: Parte 1','Ficção e Fantasia',146,2010,2.79);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (55,'Mulheres ao Ataque','Drama',102,2011,1.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (56,'Cada Um Tem a Gêmea Que Merece','Comédia',91,2011,2.09);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (57,'Jovens Adultos','Drama',94,2011,1.99);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (58,'Histórias Cruzadas','Drama',146,2011,2.49);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (59,'Pior dos Pecados','Mistério e Suspense',111,2011,2.39);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (60,'Morte Negra','Drama',102,2011,2.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (61,'Harry Potter e as Relíquias da Morte: Parte 2','Ficção e Fantasia',130,2011,1.99);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (62,'As Sessões','Drama',95,2012,2.29);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (63,'Django Livre','Ação e Aventura',165,2012,2.69);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (64,'A Viagem','Drama',172,2012,2.89);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (65,'Motoqueiro Fantasma - Espírito de Vingança','Ação e Aventura',96,2012,1.79);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (66,'Jogos Vorazes','Drama',142,2012,1.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (67,'O Ataque','Drama',131,2013,1.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (68,'Sem proteção','Mistério e Suspense',125,2013,2.39);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (69,'Sangue no Gelo','Mistério e Suspense',105,2013,2.49);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (70,'Capitão Phillips','Drama',134,2013,1.59);
INSERT INTO filmes (`id_filme`,`titulo`,`genero`,`duracao`,`ano_lancamento`,`preco_aluguel`) VALUES (71,'Rio 2','Animação',101,2014,1.79);
