-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE Usuario (
ID VARCHAR(10) PRIMARY KEY,
Senha VARCHAR(10),
Email VARCHAR(30),
Login VARCHAR(30)
);

CREATE TABLE Racao (
ID VARCHAR(10) PRIMARY KEY,
Extrato VARCHAR(10),
Fibra VARCHAR(10),
Proteina VARCHAR(10),
NomeRacao VARCHAR(30),
Mineral VARCHAR(10),
Umidade VARCHAR(10)
);

CREATE TABLE Relacao 4 (
ID VARCHAR(10),
-- Erro: nome do campo duplicado nesta tabela!
ID VARCHAR(10),
FOREIGN KEY(ID) REFERENCES Racao (ID) ON UPDATE SET NULL ON DELETE SET NULL
);

CREATE TABLE Preco (
ID VARCHAR(10) PRIMARY KEY,
ValorFeijao DECIMAL(10,2),
ValorArroz DECIMAL(10,2),
ValorCarne DECIMAL(10,2),
ValorFrango DECIMAL(10,2),
ValorCenoura DECIMAL(10,2)
);

CREATE TABLE Relacao 5 (
ID VARCHAR(10),
-- Erro: nome do campo duplicado nesta tabela!
ID VARCHAR(10),
FOREIGN KEY(ID) REFERENCES Preco (ID) ON UPDATE SET NULL ON DELETE SET NULL
);

CREATE TABLE Animal (
ID VARCHAR(10) PRIMARY KEY,
Usuario VARCHAR(60),
Cor VARCHAR(10),
Altura DECIMAL(10,3),
Nome VARCHAR(30),
Tipo VARCHAR(10),
Peso DECIMAL(10,3),
Raca VARCHAR(30),
Sexo CHAR(1),
Nascimento DATE
);

CREATE TABLE Alimento (
ID VARCHAR(10) PRIMARY KEY,
Animal VARCHAR(10),
Nome VARCHAR(30),
Recomendado VARCHAR(80),
FOREIGN KEY(Animal) REFERENCES Animal (ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE Vacina (
ID VARCHAR(10) PRIMARY KEY,
Animal VARCHAR(10),
Estabelecimento VARCHAR(50),
Nome VARCHAR(20),
DataProximaAplicacao DATETIME,
DataAplicacao DATETIME,
FOREIGN KEY(Animal) REFERENCES Animal (ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE Higiene (
ID VARCHAR(10) PRIMARY KEY,
Animal VARCHAR(10),
Tipo VARCHAR(10),
Estabelecimento VARCHAR(50),
DataProcedimento DATETIME,
FOREIGN KEY(Animal) REFERENCES Animal (ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE Relacao 6 (
ID VARCHAR(10),
-- Erro: nome do campo duplicado nesta tabela!
ID VARCHAR(10),
FOREIGN KEY(ID) REFERENCES Usuario (ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
FOREIGN KEY(ID) REFERENCES Animal (ID) ON UPDATE RESTRICT ON DELETE RESTRICT
);

ALTER TABLE Relacao 4 ADD FOREIGN KEY(ID) REFERENCES Animal (ID) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE Relacao 5 ADD FOREIGN KEY(ID) REFERENCES Animal (ID) ON UPDATE SET NULL ON DELETE SET NULL;
