-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE PROJETO (
	PROJ_COD INTEGER PRIMARY KEY,
	PROJ_NOME VARCHAR(30)
);

CREATE TABLE FUNCIONARIO (
	FUNC_MATRICULA INTEGER PRIMARY KEY,
	FUNC_NOME VARCHAR(30),
	FUNC_ENDERECO VARCHAR(200),
	FUNC_DATA_INICIO DATETIME,
	FUNC_TEMPO_ALOCACAO VARCHAR(10),
	PROJ_COD INTEGER,
	FOREIGN KEY(PROJ_COD) REFERENCES PROJETO (PROJ_COD) ON UPDATE RESTRICT ON DELETE RESTRICT
);
