-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE FUNCIONARIOS (
REGISTRO INTEGER PRIMARY KEY,
NOME VARCHAR(30),
ADMISSAO VARCHAR(10),
SEXO CHAR(1),
DEPARTAMENTO VARCHAR(10),
CARGO INTEGER
);

CREATE TABLE CARGO (
CODIGO INTEGER PRIMARY KEY,
NUMERO VARCHAR(10),
SALARIO DECIMAL(10,2)
);

ALTER TABLE FUNCIONARIOS ADD FOREIGN KEY(CARGO) REFERENCES CARGO (CODIGO)
