-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE PRODUTOS (
	CODIGO INTEGER PRIMARY KEY,
	DESCRICAO VARCHAR(30),
	UNIDADE VARCHAR(10),
	VALOR DECIMAL(10,2),
	CLACIFICACAO VARCHAR(10),
	CUSTO DECIMAL(10,2)
);
