-- CRIANDO PROCEDIMENTOS PARA TRAZER OS TELEFONES DE ACORDO COM O TIPO PASSADO.

CREATE PROCEDURE TELEFONES @TIPO CHAR(3)
AS (
	SELECT NOME, NUMERO 
	FROM PESSOA INNER JOIN TELEFONE
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = @TIPO
	)
GO 

-- CRIANDO PROCEDIMENTOS COM PARAMETROS DE ENTRADA E PARAMETRO DE SAIDA.

CREATE PROCEDURE GETTIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS (
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE
	WHERE TIPO = @TIPO
	) 
GO

-- CRIANDO PROCEDIMENTO DE CADASTRO.

CREATE PROCEDURE CADASTRO (
	@NOME VARCHAR(30),
	@SEXO CHAR(1),
	@NASCIMENTO DATE,
	@TIPO CHAR(3),
	@NUMERO VARCHAR(10)
	)
AS 
	DECLARE @FK INT
	INSERT INTO PESSOA VALUES(@NOME, @SEXO, @NASCIMENTO) -- GERAR UM ID
	SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY)
	INSERT INTO TELEFONE VALUES(@TIPO, @NUMERO, @FK)
	
GO 



