CREATE TABLE PESSOA(
	IDPESSOA INT IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL,
	NASCIMENTO DATE NOT NULL,
	CONSTRAINT PK_IDPESSOA PRIMARY KEY(IDPESSOA),
	CONSTRAINT CK_SEXO CHECK(SEXO IN('M','F'))
)
GO  


CREATE TABLE TELEFONE(
	IDTELEFONE INT IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT,
	CONSTRAINT PK_IDTELEFONE PRIMARY KEY(IDTELEFONE),
	CONSTRAINT CK_TIPO CHECK(TIPO IN ('CEL','COM','RES')),
	CONSTRAINT FK_IDTELEFONE_IDPESSOA FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
)
GO  
