-- CREATING THE TELEPHONE TABLE WITH THE 1 X N REALIZATION.

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK (TIPO IN ('RES','COM','CEL')),
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT 
)
GO  
