-- CREATING THE ADDRESS TABLE WITH THE 1 X 1 REALIZATION.

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY IDENTITY(100,10),
	BAIRRO VARCHAR(30),
	UF CHAR(2) NOT NULL CHECK (UF IN('RJ','SP','MG')),
	ID_ALUNO INT UNIQUE
)
GO 