SHOW DATESTYLE;

/*
ISO, DMY
*/


-- MUDANDO O ESTILO DE DATA DERETAMENTE NO ARQUIVO DO 'PostgreSQL'.
-- CAMINHO DO ARQUIVO: C:\Program Files\PostgreSQL\10\data\postgresql.conf
-- DEVE-SE ABRIR O ARQUIVO COM O 'Notepad++' E PROCURAR 'datestyle'.
-- DEPOIS DE TER SALVO O ARQUIVO MODIFICADO, DEVE-SE REINICIAR O SERVIÇO 'PostgreSQL'
-- FEITO ISSO, BASTA FAZER O 'Resfresh...' E CONFERIR.


SHOW DATESTYLE;

/*
ISO, MDY
*/
