DROP TABLE LOCACAO;

/*
Query returned successfully in 1 secs 45 msec.
*/


CREATE TABLE LOCACAO(
	IDLOCACAO INT,
	DATA TIMESTAMP,
	MIDIA INT,
	DIAS INT,
	ID_FILME INT,
	CONSTRAINT PK_LOCACAO PRIMARY KEY(IDLOCACAO),
	CONSTRAINT FK_LOCACAO_FILME FOREIGN KEY(ID_FILME) REFERENCES FILME(IDFILME)
);

/*
Query returned successfully in 1 secs 961 msec
*/

CREATE SEQUENCE SEQ_LOCACAO;

/*
Query returned successfully in 376 msec.
*/

NEXTVAL('SEQ_LOCACAO');


CREATE TABLE RELATORIO_LOCADORA AS 
SELECT L.IDLOCACAO, F.NOME AS "FILME", G.NOME AS "GENERO", L.DATA AS "DATA", L.DIAS AS "DIA", L.MIDIA AS "MIDIA"
FROM GENERO G
INNER JOIN FILME F 
ON G.IDGENERO = F.ID_GENERO
INNER JOIN LOCACAO L 
ON L.ID_FILME = F.IDFILME;

/*
Query returned successfully in 425 msec.
*/

