CREATE TABLE GENERO(
	IDGENERO INT,
	NOME VARCHAR(30),
	CONSTRAINT PK_IDGENERO PRIMARY KEY(IDGENERO)
);


CREATE TABLE FILME(
	IDFILME INT,
	NOME VARCHAR(50),
	ANO INT,
	ID_GENERO INT,
	CONSTRAINT PK_IDFILME PRIMARY KEY(IDFILME),
	CONSTRAINT FK_FILME_GENERO FOREIGN KEY(ID_GENERO) REFERENCES GENERO(IDGENERO)
);

CREATE TABLE LOCACAO(
	IDLOCACAO INT,
	DATA DATE,
	MIDIA INT,
	DIAS INT,
	ID_FILME INT,
	CONSTRAINT PK_LOCACAO PRIMARY KEY(IDLOCACAO),
	CONSTRAINT FK_LOCACAO_FILME FOREIGN KEY(ID_FILME) REFERENCES FILME(IDFILME)
);



CREATE TABLE REL_LOCADORA AS   
SELECT F.NOME AS "FILME", G.NOME AS "GENERO", L.DATA AS "DATA", L.DIAS AS "DIAS", L.MIDIA AS "MIDIA" 
FROM GENERO G
INNER JOIN FILME F ON G.IDGENERO = F.ID_GENERO
INNER JOIN LOCACAO L ON F.IDFILME = L.ID_FILME;
