-- Criando uma constraint PK_CLIENTE e alterando IDCLIENTE para uma chave primaria.

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(IDCLIENTE);

-- Criando uma constraint PK_CLIENTE_TELEFONE e alterando ID_CLIENTE em uma chave estrangeira.

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

-- Verificando se as constraint foram criadas corretamente.

SHOW CREATE TABLE TELEFONE;

/*
| TELEFONE | CREATE TABLE `telefone` (
  `IDTELEFONE` int DEFAULT NULL,
  `TIPO` char(3) NOT NULL,
  `NUMERO` varchar(10) NOT NULL,
  `ID_CLIENTE` int DEFAULT NULL,
  KEY `FK_CLIENTE_TELEFONE` (`ID_CLIENTE`),
  CONSTRAINT `FK_CLIENTE_TELEFONE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`IDCLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/