INSERT INTO POKEMONS VALUES (1, 'Bulbasaur', 7, 69, 64)
INSERT INTO POKEMONS VALUES (4, 'Charmander', 6, 85, 62)
INSERT INTO POKEMONS VALUES (7, 'Squirtle', 5, 90, 63)
INSERT INTO POKEMONS VALUES (25, 'Pikachu', 4, 60, 112)
INSERT INTO POKEMONS VALUES (145, 'Zapdos', 16, 526, 261)
INSERT INTO POKEMONS VALUES (146, 'Moltres', 20, 600, 261)
INSERT INTO POKEMONS VALUES (150, 'Mewtwo', 20, 1220, 306)
GO 


INSERT INTO POKEMON_TIPOS VALUES (1, 'grass')
INSERT INTO POKEMON_TIPOS VALUES (1, 'poison')
INSERT INTO POKEMON_TIPOS VALUES (4, 'fire')
INSERT INTO POKEMON_TIPOS VALUES (25, 'electric')
INSERT INTO POKEMON_TIPOS VALUES (144, 'ice')
INSERT INTO POKEMON_TIPOS VALUES (144, 'fliying')
INSERT INTO POKEMON_TIPOS VALUES (146, 'fire')
INSERT INTO POKEMON_TIPOS VALUES (146, 'fliying')
INSERT INTO POKEMON_TIPOS VALUES (151, 'psychic')
GO  


INSERT INTO JOKENPO VALUES ('pedra')
INSERT INTO JOKENPO VALUES ('papel')
INSERT INTO JOKENPO VALUES ('tesoura')
GO  
