-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.

CREATE DATABASE TOP_UNIFORMES;

USE TOP_UNIFORMES;

-- CRIANDO A TABELA VENDEDORES -------------------------- ORDEM 01

CREATE TABLE VENDEDORES (
	VEN_CHAVE INT PRIMARY KEY AUTO_INCREMENT,
	VEN_NOME VARCHAR(30) NOT NULL,
	VEN_CNPJ_CPF VARCHAR(18) NOT NULL,
	VEN_TIPOPESSOA CHAR(1) NOT NULL,
	VEN_INSCRESTADUAL VARCHAR(25) NOT NULL,
	VEN_STATUS VARCHAR(15) NOT NULL,
	VEN_EMAIL VARCHAR(60) NOT NULL,
	VEN_VPERCENT_COMIS NUMERIC(5,4) NOT NULL
);

-- CRIANDO A TABELA CLIENTES ---------------------------- ORDEM 01

CREATE TABLE CLIENTES (
	CLI_CHAVE INT PRIMARY KEY AUTO_INCREMENT,
	CLI_TIPOPESSOA CHAR(1) NOT NULL,
	CLI_EMAIL VARCHAR(60) NOT NULL,
	CLI_STATUS VARCHAR(15) NOT NULL,
	CLI_BAIRRO VARCHAR(30) NOT NULL,
	CLI_ESTADO CHAR(2) NOT NULL,
	CLI_PAIS VARCHAR(10) NOT NULL,
	CLI_INSCRESTADUAL VARCHAR(25) NOT NULL,
	CLI_CEP VARCHAR(9) NOT NULL,
	CLI_CIDADE VARCHAR(35) NOT NULL,
	CLI_CNPJ_CPF VARCHAR(18) NOT NULL,
	CLI_ENDERECO VARCHAR(60) NOT NULL,
	CLI_RAZAOSOCIAL VARCHAR(60) NOT NULL,
	CLI_NOMEFANTASIA VARCHAR(30) NOT NULL
);

-- CRIANDO A TABELA PRODUTOS ---------------------------- ORDEM 01

CREATE TABLE PRODUTOS (
	PROD_CHAVE INT PRIMARY KEY AUTO_INCREMENT,
	PROD_FAMILI VARCHAR(10) NOT NULL,
	PROD_DESCRICAO VARCHAR(60) NOT NULL,
	PROD_UNIDAD VARCHAR(5) NOT NULL,
	PROD_VPRECO NUMERIC(18,4) NOT NULL,
	CAT_XDESCRI_X VARCHAR(5120) NOT NULL
);

-- CRIANDO A TABELA VENDAS ------------------------------ ORDEM 02

CREATE TABLE VENDAS (
	VDA_CHAVE INT PRIMARY KEY AUTO_INCREMENT,
	VDA_DATAMOVTO DATE NOT NULL,
	VDA_VDINHEIRO NUMERIC(18,2) NOT NULL,
	VDA_VCARTAO NUMERIC(18,2) NOT NULL,
	VDA_VCHAQUE NUMERIC(18,2) NOT NULL,
	VDA_VPRAZO NUMERIC(18,2) NOT NULL,
	VDA_VOUTROS NUMERIC(18,2) NOT NULL,
	VDA_VTOTAL NUMERIC(18,2) NOT NULL,
	VDA_VRECEBIDO NUMERIC(18,2) NOT NULL,
	VDA_VDESC NUMERIC(18,2) NOT NULL,
	VDA_VTROCO NUMERIC(18,2) NOT NULL,
	CLI_CHAVE INT UNIQUE,
	VEN_CHAVE INT UNIQUE,
	
	FOREIGN KEY(CLI_CHAVE) REFERENCES CLIENTES (CLI_CHAVE),
	FOREIGN KEY(VEN_CHAVE) REFERENCES VENDEDORES (VEN_CHAVE)
);

-- CRIANDO A TABELA VENDA_ITENS ------------------------- ORDEM 03

CREATE TABLE VENDA_ITENS (
	VDI_CHAVE_VDA INT AUTO_INCREMENT,
	VDI_NSEQUEN INT NOT NULL,
	VDI_CODPRO_PROD VARCHAR(10) NOT NULL,
	VDI_QQUANTI NUMERIC(18,6) NOT NULL,
	VDI_DESCPROD VARCHAR(255) NOT NULL,
	VDI_VPREUNI VARCHAR(10) NOT NULL,
	VDI_VALORITEM NUMERIC(18,2) NOT NULL,
	VDI_PERCENTDESC NUMERIC(5,2) NOT NULL,
	VDI_QTDEDEVOLV NUMERIC(18,2) NOT NULL,
	VDA_CHAVE INT NOT NULL,
	PROD_CHAVE INT NOT NULL,
	PRIMARY KEY(VDI_CHAVE_VDA,VDI_NSEQUEN),

	FOREIGN KEY(VDA_CHAVE) REFERENCES VENDAS (VDA_CHAVE),
	FOREIGN KEY(PROD_CHAVE) REFERENCES PRODUTOS (PROD_CHAVE)
);


/* Inserindo Registros na tabela Produtos*/

INSERT INTO PRODUTOS(PROD_FAMILI,PROD_DESCRICAO,PROD_UNIDAD,PROD_VPRECO) VALUES('ESCRITORIO','NOBREAK','1',200);
INSERT INTO PRODUTOS(PROD_FAMILI,PROD_DESCRICAO,PROD_UNIDAD,PROD_VPRECO) VALUES('ESCRITORIO','NOTEBOOK','1',2500);
INSERT INTO PRODUTOS(PROD_FAMILI,PROD_DESCRICAO,PROD_UNIDAD,PROD_VPRECO) VALUES('LIMPEZA','SABÃO EM PÓ','1',9.00);
INSERT INTO PRODUTOS(PROD_FAMILI,PROD_DESCRICAO,PROD_UNIDAD,PROD_VPRECO) VALUES('CAMA','FRONHA PARA TRAVESSEIRO','1',5.59);
INSERT INTO PRODUTOS(PROD_FAMILI,PROD_DESCRICAO,PROD_UNIDAD,PROD_VPRECO) VALUES('BANHO','TOALHA BRANCA','1',5.59);


ALTER TABLE PRODUTOS MODIFY PROD_VPRECO NUMERIC(18,2) NOT NULL;








