ALTER TABLE FICHA
ADD CONSTRAINT FK_ALUNO_FICHA
FOREIGN KEY (ID_ALUNO)
REFERENCES ALUNO (IDALUNO);

SHOW CREATE TABLE FICHA;

/*
| FICHA | CREATE TABLE `ficha` (
  `IDFICHA` int NOT NULL AUTO_INCREMENT,
  `DATA_NASC` date NOT NULL,
  `ALTURA` float DEFAULT NULL,
  `PESO` float DEFAULT NULL,
  `ID_ALUNO` int NOT NULL,
  PRIMARY KEY (`IDFICHA`),
  UNIQUE KEY `ID_ALUNO` (`ID_ALUNO`),
  CONSTRAINT `FK_ALUNO_FICHA` FOREIGN KEY (`ID_ALUNO`) REFERENCES `aluno` (`IDALUNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/
