-- DESCRIPTION COMMANDS.
-- PROCEDURES - COMMANDS CREATED AND STORED ALREADY IN THE SQL SERVER SYSTEM.


SP_COLUMNS ALUNO
GO

/*
TABLE_QUALIFIER	TABLE_OWNER	TABLE_NAME	COLUMN_NAME	DATA_TYPE	TYPE_NAME		PRECISION	LENGTH	SCALE	RADIX	NULLABLE	REMARKS	COLUMN_DEF	SQL_DATA_TYPE	SQL_DATETIME_SUB	CHAR_OCTET_LENGTH	ORDINAL_POSITION	IS_NULLABLE	SS_DATA_TYPE

ESCOLA			dbo			ALUNO		IDALUNO		4			int identity	10			4		0		10		0			NULL	NULL		4				NULL				NULL				1					NO			56
ESCOLA			dbo			ALUNO		NOME		12			varchar			30			30		NULL	NULL	0			NULL	NULL		12				NULL				30					2					NO			39
ESCOLA			dbo			ALUNO		SEXO		1			char			1			1		NULL	NULL	0			NULL	NULL		1				NULL				1					3					NO			47
ESCOLA			dbo			ALUNO		NASCIMENTO	-9			date			10			20		NULL	NULL	0			NULL	NULL		-9				NULL				NULL				4					NO			0
ESCOLA			dbo			ALUNO		EMAIL		12			varchar			30			30		NULL	NULL	1			NULL	NULL		12				NULL				30					5					YES			39
*/

SP_HELP ALUNO
GO

/*
...
*/

SP_COLUMNS ENDERECO
GO

/*
TABLE_QUALIFIER	TABLE_OWNER	TABLE_NAME	COLUMN_NAME	DATA_TYPE	TYPE_NAME		PRECISION	LENGTH	SCALE	RADIX	NULLABLE	REMARKS	COLUMN_DEF	SQL_DATA_TYPE	SQL_DATETIME_SUB	CHAR_OCTET_LENGTH	ORDINAL_POSITION	IS_NULLABLE	SS_DATA_TYPE

ESCOLA			dbo			ENDERECO	IDENDERECO	4			int identity	10			4		0		10		0			NULL	NULL		4				NULL				NULL				1					NO			56
ESCOLA			dbo			ENDERECO	BAIRRO		12			varchar			30			30		NULL	NULL	1			NULL	NULL		12				NULL				30					2					YES			39
ESCOLA			dbo			ENDERECO	UF			1			char			2			2		NULL	NULL	0			NULL	NULL		1				NULL				2					3					NO			47
ESCOLA			dbo			ENDERECO	ID_ALUNO	4			int				10			4		0		10		1			NULL	NULL		4				NULL				NULL				4					YES			38
*/

SP_HELP ENDERECO
GO

/*
...
*/

SP_COLUMNS TELEFONE
GO

/*
TABLE_QUALIFIER	TABLE_OWNER	TABLE_NAME	COLUMN_NAME	DATA_TYPE	TYPE_NAME		PRECISION	LENGTH	SCALE	RADIX	NULLABLE	REMARKS	COLUMN_DEF	SQL_DATA_TYPE	SQL_DATETIME_SUB	CHAR_OCTET_LENGTH	ORDINAL_POSITION	IS_NULLABLE	SS_DATA_TYPE

ESCOLA			dbo			TELEFONE	IDTELEFONE	4			int identity	10			4		0		10		0			NULL	NULL		4				NULL				NULL				1					NO			56
ESCOLA			dbo			TELEFONE	TIPO		1			char			3			3		NULL	NULL	0			NULL	NULL		1				NULL				3					2					NO			47
ESCOLA			dbo			TELEFONE	NUMERO		12			varchar			10			10		NULL	NULL	0			NULL	NULL		12				NULL				10					3					NO			39
ESCOLA			dbo			TELEFONE	ID_ALUNO	4			int				10			4			0	10		1			NULL	NULL		4				NULL				NULL				4					YES			38
*/

SP_HELP TELEFONE
GO

/*
...
*/