
ALTER TABLE ENDERECO 
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY (ID_ALUNO) 
REFERENCES ALUNO (IDALUNO)
GO 


ALTER TABLE ENDERECO 
ADD CONSTRAINT FK_ENDERECO_TELEFONE
FOREIGN KEY (ID_ALUNO) 
REFERENCES ALUNO (IDALUNO)
GO 


ALTER TABLE ALUNO 
ADD CONSTRAINT PK_IDALUNO 
PRIMARY KEY (IDALUNO)
GO


ALTER TABLE ENDERECO
ADD CONSTRAINT PK_IDENDERECO 
PRIMARY KEY (IDENDERECO)
GO 


ALTER TABLE TELEFONE
ADD CONSTRAINT PK_TELEFONE
PRIMARY KEY (IDTELEFONE)
GO 


ALTER TABLE ALUNO
ADD CONSTRAINT UNIQUE_EMAIL UNIQUE (EMAIL)
GO  


ALTER TABLE ALUNO
ADD CONSTRAINT UNIQUE_ID_ALUNO UNIQUE (ID_ALUNO)
GO  

ALTER TABLE ALUNO
ADD CONSTRAINT CHECK_SEXO 
CHECK (SEXO IN ('M','F'))
GO  

ALTER TABLE TELEFONE
ADD CONSTRAINT CHECK_TIPO 
CHECK (TIPO IN ('COM','RES','CEL'))
GO  
