-- ENTERING DATA INTO THE STUDENT TABLE.

INSERT INTO ALUNO VALUES('ANDRE','M','1981/12/09','ANDRE@IG.COM')
INSERT INTO ALUNO VALUES('ANA','F','1978/03/09','ANA@IG.COM')
INSERT INTO ALUNO VALUES('RUI','M','1951/07/09','RUI@IG.COM')
INSERT INTO ALUNO VALUES('JOAO','M','2002/11/09','JOAO@IG.COM')
INSERT INTO ALUNO VALUES('ANDREIA','F','1985/12/09','ANDREIA@IG.COM')
INSERT INTO ALUNO VALUES('ANAKARLA','F','1979/03/09','ANAKARLA@IG.COM')
INSERT INTO ALUNO VALUES('ROBERVAL','M','1981/07/09','ROBERVAL@IG.COM')
INSERT INTO ALUNO VALUES('JOANETE','F','2001/10/09','JOANETE@IG.COM')
INSERT INTO ALUNO VALUES('AMANDA','F','1981/12/09','AMANDA@IG.COM')
INSERT INTO ALUNO VALUES('ADRIANO','M','1976/03/09','ADRIANO@IG.COM')
INSERT INTO ALUNO VALUES('RAFAEL','M','1991/07/09','RAFAEL@IG.COM')
INSERT INTO ALUNO VALUES('JHONATA','M','2000/11/09','JHONATA@IG.COM')
GO

-- CHECKING IF THE DATA HAVE BEEN ENTERED CORRECTLY IN THE STUDENT TABLE.

SELECT * FROM ALUNO 
GO 


-- ENTERING DATA INTO THE ADDRESS TABLE.

INSERT INTO ENDERECO VALUES('FLAMENGO','RJ',1)
INSERT INTO ENDERECO VALUES('MORUMBI','SP',2)
INSERT INTO ENDERECO VALUES('CENTRO','MG',3)
INSERT INTO ENDERECO VALUES('CENTRO','SP',4)
INSERT INTO ENDERECO VALUES('FLAMENGO','RJ',5)
INSERT INTO ENDERECO VALUES('MORUMBI','SP',6)
INSERT INTO ENDERECO VALUES('CENTRO','MG',7)
INSERT INTO ENDERECO VALUES('CENTRO','SP',8)
INSERT INTO ENDERECO VALUES('FLAMENGO','RJ',9)
INSERT INTO ENDERECO VALUES('MORUMBI','SP',10)
INSERT INTO ENDERECO VALUES('CENTRO','MG',11)
INSERT INTO ENDERECO VALUES('CENTRO','SP',12)
GO

-- CHECKING IF THE DATA HAVE BEEN ENTERED CORRECTLY IN THE ADDRESS TABLE.

SELECT * FROM ENDERECO
GO 


-- ENTERING DATA INTO THE TELEPHONE TABLE.

INSERT INTO TELEFONE VALUES('CEL','7897889',1)
INSERT INTO TELEFONE VALUES('RES','4385444',1)
INSERT INTO TELEFONE VALUES('COM','4353754',2)
INSERT INTO TELEFONE VALUES('CEL','7544556',2)
INSERT INTO TELEFONE VALUES('CEL','7899589',3)
INSERT INTO TELEFONE VALUES('RES','4325014',4)
INSERT INTO TELEFONE VALUES('COM','4344354',5)
INSERT INTO TELEFONE VALUES('CEL','2344676',5)
INSERT INTO TELEFONE VALUES('CEL','7899909',6)
INSERT INTO TELEFONE VALUES('RES','4465444',6)
INSERT INTO TELEFONE VALUES('COM','4353654',7)
INSERT INTO TELEFONE VALUES('CEL','2369556',8)
INSERT INTO TELEFONE VALUES('CEL','6889889',9)
INSERT INTO TELEFONE VALUES('RES','4324004',9)
INSERT INTO TELEFONE VALUES('COM','4345354',9)
INSERT INTO TELEFONE VALUES('CEL','2444556',10)
INSERT INTO TELEFONE VALUES('CEL','7895589',11)
INSERT INTO TELEFONE VALUES('RES','8825444',12)
INSERT INTO TELEFONE VALUES('COM','4354454',12)
INSERT INTO TELEFONE VALUES('CEL','2311556',12)
GO  


-- CHECKING IF THE DATA HAVE BEEN ENTERED CORRECTLY IN THE TELEPHONE TABLE.

SELECT * FROM TELEFONE
GO 

