/*
1ª MODELAGEM CONCEITUAL - PROGRAMA DE MODELAGEM BRMODELO 3.0
2ª MODELAGEM LÓGICA - PROGRAMA DE MODELAGEM BRMODELO 3.0
3ª MODELAGEM FÍSICA - SCRIPTS DE BANCO DE DADOS
*/

/* INICIANDO A MODELAGEM FÍSICA */
/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE LIVRARIA_2;

/* CONECTANDO-SE AO BANCO */

USE LIVRARIA_2;

/* CRIANDO A TABELA DE CLIENTE */

CREATE TABLE LIVROS_2(
	LIVRO VARCHAR(100),
	AUTOR VARCHAR(100),
	SEXO CHAR(1),
	PAGINAS INT(5),
	EDITORA VARCHAR(30),
	VALOR FLOAT(10,2),
	UF CHAR(2),
	ANO INT(4)
);

/* VERIFICANDO A BASE DE DADOS */

SHOW DATABASES;

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* VERIFICANDO EM QUAL TABELA ESTÁ CONECTADA - USANDO O COMANDO STATUS */

STATUS;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC LIVRARIA_2;

/* COLOCANDO DADOS NA TABELA COM COLUNAS - MELHOR ALTERNATIVA */

INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('Cavaleiro Real','Ana Claudia','F','465','Atlas',49.90,'RJ','2009');
INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('SQL para leigos','João Nunes','M','450','Addison',98.00,'SP','2018');
INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('Receitas Caseiras','Celia Tavares','F','210','Atlas',45.00,'RJ','2008');
INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('Pessoas Efetivas','Eduardo Santos','M','390','Beta',78.99,'RJ','2018');
INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('Habitos Saudáveis','Eduardo Santos','M','630','Beta',150.98,'RJ','2019');
INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('A Casa Marrom','Hermes Macedo','M','250','Bubba',60.00,'MG','2016');
INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('Estacio Querido','Geraldo Francisco','M','310','Insignio',100.00,'ES','2015');
INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('Pra sempre amigas','Leda Silva','F','510','Insignia',78.98,'ES','2011');
INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('Copas Inesqueciveis','Marcos Alcantara','M','200','Larson',130.98,'RS','2018');
INSERT INTO LIVROS_2(LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES('O poder da mente','Clara Mafra','F','120','Continental',56.58,'SP','2017');

/* 1 - Trazer todos os dados. */

SELECT * FROM LIVROS_2;

/* 2 - Trazer o nome do livro e o nome da editora. */

SELECT LIVRO,EDITORA FROM LIVROS_2;

/* 3 - Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino. */

SELECT LIVRO,UF FROM LIVROS_2
WHERE SEXO = 'M';

SELECT SEXO,LIVRO,UF FROM LIVROS_2
WHERE SEXO = 'M';

/* 4 - Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino. */

SELECT LIVRO,PAGINAS FROM LIVROS_2
WHERE SEXO = 'F';

SELECT SEXO,LIVRO,PAGINAS FROM LIVROS_2
WHERE SEXO = 'F';

/* 5 - Trazer os valores dos livros das editores de São Paulo. */

SELECT LIVRO, VALOR FROM LIVROS_2
WHERE UF = 'SP';

SELECT UF, LIVRO, VALOR FROM LIVROS_2
WHERE UF = 'SP';

/* 6 - Trazer os dados dos autores do sexo masculino que tiveram livros publicos por São Paulo ou Rio de Janeiro (Questão Desafio). */

SELECT AUTOR, SEXO FROM LIVROS_2 WHERE SEXO = 'M' AND (UF = 'SP' OR UF = 'RJ');
SELECT AUTOR, SEXO, UF FROM LIVROS_2 WHERE SEXO = 'M' AND (UF = 'SP' OR UF = 'RJ');  /* MELHOR ALTERNATIVA */
SELECT AUTOR, SEXO, UF FROM LIVROS_2 WHERE SEXO = 'M' AND (UF IN('SP','RJ'));
SELECT * FROM LIVROS_2 WHERE UF IN('SP','RJ') AND SEXO IN('M');
SELECT * FROM LIVROS_2 WHERE (UF = 'SP' OR UF = 'RJ') AND SEXO = 'M';
