CREATE TRIGGER TRG_SALARIO
ON DBO.FUNCIONARIOS
FOR UPDATE AS
IF UPDATE(SALARIO)
BEGIN
	INSERT INTO HIST_SALARIO
	(IDFUNC, NOME, DEPARTAMENTO, CARGO, ANTI_SAL, NOVO_SAL, DATA)
	SELECT 
	D.IDFUNC, D.NOME, D.DEPARTAMENTO, D.CARGO, D.SALARIO, I.SALARIO, GETDATE()
	FROM DELETED D, INSERTED I  
	WHERE D.IDFUNC = I.IDFUNC
END  

GO 



CREATE TRIGGER TRG_HIST_SALARIO
ON DBO.FUNCIONARIOS
FOR UPDATE AS
IF UPDATE(SALARIO)
BEGIN
	INSERT INTO HIST_SALARIO
	(IDFUNC, NOME, DEPARTAMENTO, CARGO, ANTI_SAL, NOVO_SAL, DATA, USUARIO)
	SELECT 
	D.IDFUNC, D.NOME, D.DEPARTAMENTO, D.CARGO, D.SALARIO, I.SALARIO, GETDATE(), SUSER_NAME()
	FROM DELETED D, INSERTED I  
	WHERE D.IDFUNC = I.IDFUNC
END  

GO 
