CREATE TABLE FUNCIONARIOS(
	IDFUNC INT IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SEXO VARCHAR(10) NOT NULL,
	DEPARTAMENTO VARCHAR(100) NOT NULL,
	ADMISSAO DATE NOT NULL,
	SALARIO MONEY NOT NULL,
	CARGO VARCHAR(100) NOT NULL,
	IDGERENTE INT,
	CONSTRAINT PK_IDFUNC PRIMARY KEY (IDFUNC),
	CONSTRAINT UQ_EMAIL UNIQUE (EMAIL),
	CONSTRAINT FK_IDGERENTE FOREIGN KEY (IDGERENTE) REFERENCES FUNCIONARIOS (IDFUNC)
)
GO 


CREATE TABLE HIST_SALARIO(
	IDHIST INT IDENTITY,
	IDFUNC INT,
	NOME VARCHAR(100),
	DEPARTAMENTO VARCHAR(100),
	CARGO VARCHAR(100),
	ANTI_SAL MONEY,
	NOVO_SAL MONEY,
	DATA DATETIME,
	CONSTRAINT PK_IDHIST_SAL PRIMARY KEY (IDHIST)
)
GO  


CREATE TABLE SALARIO_RANGE(
	MINSAL MONEY,
	MAXSAL MONEY
)
GO  


