DELIMITER $

CREATE TRIGGER CADTOTAL
BEFORE INSERT ON VENDEDORES
FOR EACH ROW

BEGIN
	DECLARE VTOTAL, VMEDIA INT;

	SET VTOTAL = NEW.JAN + NEW.FEV + NEW.MAR;
	SET VMEDIA = (NEW.JAN + NEW.FEV + NEW.MAR) / 3;

	INSERT INTO VEND_TOTAL VALUES(NEW.NOME, NEW.JAN, NEW.FEV, NEW.MAR, VTOTAL, TMEDIA);
END 
$

DELIMITER ;