SHOW CREATE TABLE TELEFONE;

/*
| TELEFONE | CREATE TABLE `telefone` (
  `IDTELEFONE` int NOT NULL AUTO_INCREMENT,
  `TIPO` enum('RES','COM','CEL') NOT NULL,
  `NUMERO` varchar(10) NOT NULL,
  `ID_CLIENTE` int DEFAULT NULL,
  PRIMARY KEY (`IDTELEFONE`),
  KEY `FK_CLIENTE_TELEFONE` (`ID_CLIENTE`),
  CONSTRAINT `FK_CLIENTE_TELEFONE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`IDCLIENTE`),
  CONSTRAINT `telefone_ibfk_1` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`IDCLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/

-- Apagando uma CONSTRAINT

ALTER TABLE TELEFONE
DROP FOREIGN KEY telefone_ibfk_1;

SHOW CREATE TABLE TELEFONE;

/*
| TELEFONE | CREATE TABLE `telefone` (
  `IDTELEFONE` int NOT NULL AUTO_INCREMENT,
  `TIPO` enum('RES','COM','CEL') NOT NULL,
  `NUMERO` varchar(10) NOT NULL,
  `ID_CLIENTE` int DEFAULT NULL,
  PRIMARY KEY (`IDTELEFONE`),
  KEY `FK_CLIENTE_TELEFONE` (`ID_CLIENTE`),
  CONSTRAINT `FK_CLIENTE_TELEFONE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`IDCLIENTE`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/
