-- Criando os relacionamentos ou CONSTRAINTS por fora das tabelas.

ALTER TABLE TELEFONE 
ADD CONSTRAINT FK_TELEFONE_ALUNO 
FOREIGN KEY(ID_ALUNO) 
REFERENCES ALUNO (IDALUNO);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY(ID_ALUNO) 
REFERENCES ALUNO (IDALUNO);

ALTER TABLE MATRICULA 
ADD CONSTRAINT FK_ALUNO
FOREIGN KEY(ID_ALUNO) 
REFERENCES ALUNO (IDALUNO);

ALTER TABLE MATRICULA 
ADD CONSTRAINT FK_SALA
FOREIGN KEY(ID_SALA) 
REFERENCES SALA (IDSALA);

-- Conferindo se os relacionamentos(CONSTRAINT) foram feitos corretamente.

SHOW CREATE TABLE TELEFONE;

/*
| TELEFONE | CREATE TABLE `telefone` (
  `IDTELEFONE` int NOT NULL AUTO_INCREMENT,
  `TIPO` enum('CEL','RES') NOT NULL,
  `NUMERO` varchar(11) NOT NULL,
  `ID_ALUNO` int DEFAULT NULL,
  PRIMARY KEY (`IDTELEFONE`),
  KEY `FK_TELEFONE_ALUNO` (`ID_ALUNO`),
  CONSTRAINT `FK_TELEFONE_ALUNO` FOREIGN KEY (`ID_ALUNO`) REFERENCES `aluno` (`IDALUNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/

SHOW CREATE TABLE ENDERECO;

/*
| ENDERECO | CREATE TABLE `endereco` (
  `IDENDERECO` int NOT NULL AUTO_INCREMENT,
  `RUA_AV` varchar(60) NOT NULL,
  `BAIRRO` varchar(30) NOT NULL,
  `CEP` varchar(10) NOT NULL,
  `CIDADE` varchar(30) NOT NULL,
  `ESTADO` char(2) NOT NULL,
  `ID_ALUNO` int NOT NULL,
  PRIMARY KEY (`IDENDERECO`),
  UNIQUE KEY `ID_ALUNO` (`ID_ALUNO`),
  CONSTRAINT `FK_ENDERECO_ALUNO` FOREIGN KEY (`ID_ALUNO`) REFERENCES `aluno` (`IDALUNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/

SHOW CREATE TABLE MATRICULA;

/*
| MATRICULA | CREATE TABLE `matricula` (
  `ANO` char(4) NOT NULL,
  `SEMESTRE` char(1) NOT NULL,
  `ID_ALUNO` int NOT NULL,
  `ID_SALA` int NOT NULL,
  PRIMARY KEY (`ID_ALUNO`,`ID_SALA`,`ANO`,`SEMESTRE`),
  KEY `FK_SALA` (`ID_SALA`),
  CONSTRAINT `FK_ALUNO` FOREIGN KEY (`ID_ALUNO`) REFERENCES `aluno` (`IDALUNO`),
  CONSTRAINT `FK_SALA` FOREIGN KEY (`ID_SALA`) REFERENCES `sala` (`IDSALA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci |
*/

