-- CREATING THE ADDRESS TABLE WITH THE 1 X 1 REALIZATION.

CREATE TABLE ENDERECO(
	IDENDERECO INT IDENTITY(100,10),
	BAIRRO VARCHAR(30) NOT NULL,
	UF CHAR(2) NOT NULL,
	ID_ALUNO INT UNIQUE
)
GO 

-- CREATING PRIMARY KEY ON IDENDERECO COLUMN.

ALTER TABLE ENDERECO
ADD CONSTRAINT PK_IDENDERECO 
PRIMARY KEY (IDENDERECO)
GO  

-- CREATING THE CHECK RELATIONSHIP BETWEEN ADDRESS AND UF.

ALTER TABLE ENDERECO
ADD CONSTRAINT CK_UF
CHECK (UF IN ('RJ','SE','SP','PE','CE','RS','AL'))
GO 

-- CREATING THE RELATIONSHIP BETWEEN STUDENT AND ADDRESS.

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_ALUNO
FOREIGN KEY (ID_ALUNO)
REFERENCES ALUNO (IDALUNO)
GO  

-- DESCRIPTION COMMANDS.
-- PROCEDURES - COMMANDS CREATED AND STORED ALREADY IN THE SQL SERVER SYSTEM.

SP_COLUMNS ENDERECO
GO 

SP_HELP ENDERECO
GO 
