-- CREATING THE TELEPHONE TABLE WITH THE 1 X N REALIZATION.

CREATE TABLE TELEFONE(
	IDTELEFONE INT IDENTITY,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_ALUNO INT 
)
GO 

-- CREATING PRIMARY KEY ON IDTELEFONE COLUMN.

ALTER TABLE TELEFONE
ADD CONSTRAINT PK_TELEFONE
PRIMARY KEY (IDTELEFONE)
GO 

-- CREATING THE CHECK RELATIONSHIP BETWEEN TELEPHONE AND TYPE.

ALTER TABLE TELEFONE
ADD CONSTRAINT CK_TIPO 
CHECK (TIPO IN ('COM','RES','CEL'))
GO 

-- CREATING THE RELATIONSHIP BETWEEN STUDENT AND TELEPHONE.

ALTER TABLE TELEFONE
ADD CONSTRAINT FK_TELEFONE_ALUNO
FOREIGN KEY (ID_ALUNO)
REFERENCES ALUNO (IDALUNO)
GO 

-- DESCRIPTION COMMANDS.
-- PROCEDURES - COMMANDS CREATED AND STORED ALREADY IN THE SQL SERVER SYSTEM.

SP_COLUMNS TELEFONE
GO 

SP_HELP TELEFONE
GO 
