-- BLOCO DE EXECUÇÃO

BEGIN
	PRINT 'PRIMEIRO BLOCO'
END   
GO  

/*
PRIMEIRO BLOCO
*/



-- BLOCOS DE ATRIBUIÇÃO DE VARIAVEIS

DECLARE
	@CONTADOR INT  
BEGIN
	SET @CONTADOR = 2022
	PRINT @CONTADOR
END   
GO  

/*
2022
*/



-- NO SQL SERVER CADA COLUNA, VARIAVEL LOCAL, EXPRESSÃO E PARAMETRO TEM UM TIPO.

DECLARE
	@V_NUMERO NUMERIC(10,2) = 100.52	
BEGIN
	PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
END
GO 

/*
VALOR NUMERICO: 100.52
VALOR NUMERICO: 100.52
*/



DECLARE	
	@V_DATA DATETIME = GETDATE()
BEGIN
	PRINT 'DATA ATUAL: ' + CAST(@V_DATA AS VARCHAR)
	PRINT 'DATA ATUAL: ' + CONVERT(VARCHAR, @V_DATA, 121) -- Padrão ODBC canônico (com milissegundos)
	PRINT 'DATA ATUAL: ' + CONVERT(VARCHAR, @V_DATA, 120) -- Padrão ODBC canônico
	PRINT 'DATA ATUAL: ' + CONVERT(VARCHAR, @V_DATA, 110) -- Padrão Europa + milissegundos
	PRINT 'DATA ATUAL: ' + CONVERT(VARCHAR, @V_DATA, 105) -- Padrão Italiano
	PRINT 'DATA ATUAL: ' + CONVERT(VARCHAR, @V_DATA, 103) -- Padrão Britânico/Francês
	PRINT 'DATA ATUAL: ' + CONVERT(VARCHAR, @V_DATA, 104) -- Padrão Alemão	
END
GO 

/*
DATA ATUAL: Jan 18 2022  6:43PM
DATA ATUAL: 2022-01-18 18:43:13.670
DATA ATUAL: 2022-01-18 18:43:13
DATA ATUAL: 01-18-2022
DATA ATUAL: 18-01-2022
DATA ATUAL: 18/01/2022
DATA ATUAL: 18.01.2022
*/

