DECLARE 
	@VAR INT = 1
BEGIN
	WHILE(@VAR < 15)
	BEGIN
		PRINT 'VALOR DE @VAR = ' + CAST(@VAR AS VARCHAR)
		SET @VAR = @VAR + 1
	END  
END  
GO    

/*
VALOR DE @VAR = 1
VALOR DE @VAR = 2
VALOR DE @VAR = 3
VALOR DE @VAR = 4
VALOR DE @VAR = 5
VALOR DE @VAR = 6
VALOR DE @VAR = 7
VALOR DE @VAR = 8
VALOR DE @VAR = 9
VALOR DE @VAR = 10
VALOR DE @VAR = 11
VALOR DE @VAR = 12
VALOR DE @VAR = 13
VALOR DE @VAR = 14
*/


DECLARE
	@VAR_CONTADOR INT = 1,
	@VAR_ACUMULADOR INT = 1
BEGIN
	WHILE (@VAR_CONTADOR <= 10)
	BEGIN
		PRINT 'CONTADOR: ' + CAST(@VAR_CONTADOR AS VARCHAR) + ' | ACUMULADOR: ' + CAST(@VAR_ACUMULADOR AS VARCHAR)
		SET @VAR_ACUMULADOR = @VAR_ACUMULADOR + @VAR_CONTADOR
		SET @VAR_CONTADOR += 1
	END	
END  
GO

/*
CONTADOR: 1 | ACUMULADOR: 1
CONTADOR: 2 | ACUMULADOR: 2
CONTADOR: 3 | ACUMULADOR: 4
CONTADOR: 4 | ACUMULADOR: 7
CONTADOR: 5 | ACUMULADOR: 11
CONTADOR: 6 | ACUMULADOR: 16
CONTADOR: 7 | ACUMULADOR: 22
CONTADOR: 8 | ACUMULADOR: 29
CONTADOR: 9 | ACUMULADOR: 37
CONTADOR: 10 | ACUMULADOR: 46
*/

