DECLARE
	@VAR_LOGGER_USER VARCHAR
BEGIN
	IF (@VAR_LOGGER_USER = 'FALSE')
		SELECT 'USUARIO LOGADO' AS 'STATUS DO USUARIO'
	ELSE  
		SELECT 'USUARIO PRECISA LOGAR' AS 'STATUS DO USUARIO'
END  
GO   

/*
STATUS DO USUARIO
---------------------
USUARIO PRECISA LOGAR

(1 linha(s) afetadas)
*/
